cloud:
  aws:
    credentials:
      access-key: AKIAIQQU5MB5QR733HHA
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: newhellobucket
